apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerador-documento
  
spec:
  selector:
    matchLabels:
      app: gerador-documento
  template:
    metadata:
      labels:
        app: gerador-documento
    spec:
      containers:
      - name: gerador-documento
        image: harrisonlima/gerador-documento
        ports:
        - containerPort: 5002
        env:
          - name: URL_GERADOR_CPF
            value: "gerador-cpf:5000"
          - name: URL_GERADOR_RG
            value: "gerador-rg:5000"
          - name: JAEGER_HOST
            value: "jaeger-agent.jaeger.svc.cluster.local"
          - name: JAEGER_PORT
            value: "6831"
          - name: JAEGER_SERVICE_NAME
            value: "gerador-documento" 