apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerador-rg
  
spec:
  selector:
    matchLabels:
      app: gerador-rg
  template:
    metadata:
      labels:
        app: gerador-rg
    spec:
      containers:
      - name: gerador-rg
        image: harrisonlima/gerador-rg
        ports:
        - containerPort: 5000
        env:
          - name: JAEGER_HOST
            value: "jaeger-agent.jaeger.svc.cluster.local"
          - name: JAEGER_PORT
            value: "6831"
          - name: JAEGER_SERVICE_NAME
            value: "gerador-rg" 