apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerador-rg
  
spec:
  selector:
    matchLabels:
      app: gerador-rg
  template:
    metadata:
      labels:
        app: gerador-rg
    spec:
      containers:
      - name: gerador-rg
        image: harrisonlima/gerador-rg
        ports:
        - containerPort: 5004
        env:
          - name: JAEGER_HOST
            value: "jaeger"
          - name: JAEGER_PORT
            value: "JAEGER_PORT"
          - name: JAEGER_SERVICE_NAME
            value: "gerador-rg" 